
export const data = {
      Ports: [
["Protocol", "Port", "Application protocol", "System service name"],
["GRE", "n/a", "GRE (IP protocol 47)", "Routing and Remote Access"],
["ESP", "n/a", "IPsec ESP (IP protocol 50)", "Routing and Remote Access"],
["AH", "n/a", "IPsec AH (IP protocol 51)", "Routing and Remote Access"],
["TCP", 7, "Echo", "Simple TCP/IP Services"],
["UDP", 7, "Echo", "Simple TCP/IP Services"],
["TCP", 9, "Discard", "Simple TCP/IP Services"],
["UDP", 9, "Discard", "Simple TCP/IP Services"],
["TCP", 13, "Daytime", "Simple TCP/IP Services"],
["UDP", 13, "Daytime", "Simple TCP/IP Services"],
["TCP", 17, "Quotd", "Simple TCP/IP Services"],
["UDP", 17, "Quotd", "Simple TCP/IP Services"],
["TCP", 19, "Chargen", "Simple TCP/IP Services"],
["UDP", 19, "Chargen", "Simple TCP/IP Services"],
["TCP", 20, "FTP default data", "FTP Publishing Service"],
["TCP", 21, "FTP control", "FTP Publishing Service"],
["TCP", 21, "FTP control", "Application Layer Gateway Service"],
["TCP", 23, "Telnet", "Telnet"],
["TCP", 25, "SMTP", "Simple Mail Transfer Protocol"],
["UDP", 25, "SMTP", "Simple Mail Transfer Protocol"],
["TCP", 25, "SMTP", "Exchange Server"],
["UDP", 25, "SMTP", "Exchange Server"],
["TCP", 42, "WINS Replication", "Windows Internet Name Service"],
["UDP", 42, "WINS Replication", "Windows Internet Name Service"],
["TCP", 53, "DNS", "DNS Server"],
["UDP", 53, "DNS", "DNS Server"],
["TCP", 53, "DNS", "Internet Connection Firewall/Internet Connection Sharing"],
["UDP", 53, "DNS", "Internet Connection Firewall/Internet Connection Sharing"],
["UDP", 67, "DHCP Server", "DHCP Server"],
["UDP", 67, "DHCP Server", "Internet Connection Firewall/Internet Connection Sharing"],
["UDP", 69, "TFTP", "Trivial FTP Daemon Service"],
["TCP", 80, "HTTP", "Windows Media Services"],
["TCP", 80, "HTTP", "World Wide Web Publishing Service"],
["TCP", 80, "HTTP", "SharePoint Portal Server"],
["TCP", 88, "Kerberos", "Kerberos Key Distribution Center"],
["UDP", 88, "Kerberos", "Kerberos Key Distribution Center"],
["TCP", 102, "X.400", "Microsoft Exchange MTA Stacks"],
["TCP", 110, "POP3", "Microsoft POP3 Service"],
["TCP", 110, "POP3", "Exchange Server"],
["TCP", 119, "NNTP", "Network News Transfer Protocol"],
["UDP", 123, "NTP", "Windows Time"],
["UDP", 123, "SNTP", "Windows Time"],
["TCP", 135, "RPC", "Message Queuing"],
["TCP", 135, "RPC", "Remote Procedure Call"],
["TCP", 135, "RPC", "Exchange Server"],
["TCP", 135, "RPC", "Certificate Services"],
["TCP", 135, "RPC", "Cluster Service"],
["TCP", 135, "RPC", "Distributed File System"],
["TCP", 135, "RPC", "Distributed Link Tracking"],
["TCP", 135, "RPC", "Distributed Transaction Coordinator"],
["TCP", 135, "RPC", "Event Log"],
["TCP", 135, "RPC", "Fax Service"],
["TCP", 135, "RPC", "File Replication"],
["TCP", 135, "RPC", "Group Policy"],
["TCP", 135, "RPC", "Local Security Authority"],
["TCP", 135, "RPC", "Remote Storage Notification"],
["TCP", 135, "RPC", "Remote Storage Server"],
["TCP", 135, "RPC", "Systems Management Server 2.0"],
["TCP", 135, "RPC", "Terminal Services Licensing"],
["TCP", 135, "RPC", "Terminal Services Session Directory"],
["UDP", 137, "NetBIOS Name Resolution", "Computer Browser"],
["UDP", 137, "NetBIOS Name Resolution", "Server"],
["UDP", 137, "NetBIOS Name Resolution", "Windows Internet Name Service"],
["UDP", 137, "NetBIOS Name Resolution", "Net Logon"],
["UDP", 137, "NetBIOS Name Resolution", "Systems Management Server 2.0"],
["UDP", 138, "NetBIOS Datagram Service", "Computer Browser"],
["UDP", 138, "NetBIOS Datagram Service", "Messenger"],
["UDP", 138, "NetBIOS Datagram Service", "Server"],
["UDP", 138, "NetBIOS Datagram Service", "Net Logon"],
["UDP", 138, "NetBIOS Datagram Service", "Distributed File System"],
["UDP", 138, "NetBIOS Datagram Service", "Systems Management Server 2.0"],
["UDP", 138, "NetBIOS Datagram Service", "License Logging Service"],
["TCP", 139, "NetBIOS Session Service", "Computer Browser"],
["TCP", 139, "NetBIOS Session Service", "Fax Service"],
["TCP", 139, "NetBIOS Session Service", "Performance Logs and Alerts"],
["TCP", 139, "NetBIOS Session Service", "Print Spooler"],
["TCP", 139, "NetBIOS Session Service", "Server"],
["TCP", 139, "NetBIOS Session Service", "Net Logon"],
["TCP", 139, "NetBIOS Session Service", "Remote Procedure Call Locator"],
["TCP", 139, "NetBIOS Session Service", "Distributed File System"],
["TCP", 139, "NetBIOS Session Service", "Systems Management Server 2.0"],
["TCP", 139, "NetBIOS Session Service", "License Logging Service"],
["TCP", 143, "IMAP", "Exchange Server"],
["UDP", 161, "SNMP", "SNMP Service"],
["UDP", 162, "SNMP Traps Outbound", "SNMP Trap Service"],
["TCP", 389, "LDAP Server", "Local Security Authority"],
["UDP", 389, "LDAP Server", "Local Security Authority"],
["TCP", 389, "LDAP Server", "Distributed File System"],
["UDP", 389, "LDAP Server", "Distributed File System"],
["TCP", 443, "HTTPS", "HTTP SSL"],
["TCP", 443, "HTTPS", "World Wide Web Publishing Service"],
["TCP", 443, "HTTPS", "SharePoint Portal Server"],
["TCP", 443, "RPC over HTTPS", "Exchange Server 2003"],
["TCP", 445, "SMB", "Fax Service"],
["TCP", 445, "SMB", "Print Spooler"],
["TCP", 445, "SMB", "Server"],
["TCP", 445, "SMB", "Remote Procedure Call Locator"],
["TCP", 445, "SMB", "Distributed File System"],
["TCP", 445, "SMB", "License Logging Service"],
["TCP", 445, "SMB", "Net Logon"],
["TCP", 464, "Kerberos Password V5", "Net Logon"],
["UDP", 500, "IPsec ISAKMP", "Local Security Authority"],
["TCP", 515, "LPD", "TCP/IP Print Server"],
["TCP", 548, "File Server for Macintosh", "File Server for Macintosh"],
["TCP", 554, "RTSP", "Windows Media Services"],
["TCP", 563, "NNTP over SSL", "Network News Transfer Protocol"],
["TCP", 593, "RPC over HTTPS endpoint mapper", "Remote Procedure Call"],
["TCP", 593, "RPC over HTTPS", "Exchange Server"],
["TCP", 636, "LDAP SSL", "Local Security Authority"],
["UDP", 636, "LDAP SSL", "Local Security Authority"],
["TCP", 993, "IMAP over SSL", "Exchange Server"],
["TCP", 995, "POP3 over SSL", "Exchange Server"],
["TCP", 1067, "Installation Bootstrap Service", "Installation Bootstrap protocol server"],
["TCP", 1068, "Installation Bootstrap Service", "Installation Bootstrap protocol client"],
["TCP", 1270, "MOM-Encrypted", "Microsoft Operations Manager 2000"],
["TCP", 1433, "SQL over TCP", "Microsoft SQL Server"],
["TCP", 1433, "SQL over TCP", "MSSQL$UDDI"],
["UDP", 1434, "SQL Probe", "Microsoft SQL Server"],
["UDP", 1434, "SQL Probe", "MSSQL$UDDI"],
["TCP", "1512", "WINS", "Windows Internet Name Service"],
["UDP", "1512", "WINS", "Windows Internet Name Service"],
["UDP", 1645, "Legacy RADIUS", "Internet Authentication Service"],
["UDP", 1646, "Legacy RADIUS", "Internet Authentication Service"],
["UDP", 1701, "L2TP", "Routing and Remote Access"],
["TCP", 1723, "PPTP", "Routing and Remote Access"],
["TCP", 1755, "MMS", "Windows Media Services"],
["UDP", 1755, "MMS", "Windows Media Services"],
["TCP", 1801, "MSMQ", "Message Queuing"],
["UDP", 1801, "MSMQ", "Message Queuing"],
["UDP", 1812, "RADIUS Authentication", "Internet Authentication Service"],
["UDP", 1813, "RADIUS Accounting", "Internet Authentication Service"],
["TCP", "1863", "Microsoft Messenger Protocol", "MSN Messenger"],
["UDP", "1863", "Microsoft Messenger Protocol", "MSN Messenger"],
["UDP", 1900, "SSDP", "SSDP Discovery Service"],
["TCP", 2101, "MSMQ-DCs", "Message Queuing"],
["TCP", 2103, "MSMQ-RPC", "Message Queuing"],
["TCP", 2105, "MSMQ-RPC", "Message Queuing"],
["TCP", 2107, "MSMQ-Mgmt", "Message Queuing"],
["TCP", "2383", "OLAP Services 9.0", "SQL Server: Downlevel OLAP Client Support (SQL 2005)"],
["TCP", 2393, "OLAP Services 7.0 / 8.0", "SQL Server: Downlevel OLAP Client Support"],
["TCP", 2394, "OLAP Services 7.0 / 8.0", "SQL Server: Downlevel OLAP Client Support"],
["UDP", 2460, "MS Theater", "Windows Media Services"],
["UDP", 2535, "MADCAP", "DHCP Server"],
["TCP", 2701, "SMS Remote Control (control)", "SMS Remote Control Agent"],
["UDP", 2701, "SMS Remote Control (control)", "SMS Remote Control Agent"],
["TCP", 2702, "SMS Remote Control (data)", "SMS Remote Control Agent"],
["UDP", 2702, "SMS Remote Control (data)", "SMS Remote Control Agent"],
["TCP", 2703, "SMS Remote Chat", "SMS Remote Control Agent"],
["UPD", 2703, "SMS Remote Chat", "SMS Remote Control Agent"],
["TCP", 2704, "SMS Remote File Transfer", "SMS Remote Control Agent"],
["UDP", 2704, "SMS Remote File Transfer", "SMS Remote Control Agent"],
["TCP", 2725, "SQL Analysis Services", "SQL Analysis Server"],
["TCP", 2869, "UPNP", "Universal Plug and Play Device Host"],
["TCP", 2869, "SSDP event notification", "SSDP Discovery Service"],
["TCP", 3268, "Global Catalog Server", "Local Security Authority"],
["TCP", 3269, "Global Catalog Server over SSL", "Local Security Authority over SSL"],
["UDP", 3343, "Cluster Services", "Cluster Service"],
["TCP", 3389, "Terminal Services", "NetMeeting Remote Desktop Sharing"],
["TCP", 3389, "Terminal Services", "Terminal Services"],
["UDP", "3478", "STUN", "OCS A/V Edge Server for STUN Communications"],
["UDP", 3527, "MSMQ-Ping", "Message Queuing"],
["UDP", 4011, "BINL", "Remote Installation"],
["UDP", 4500, "NAT-T", "Local Security Authority"],
["TCP", 5000, "SSDP legacy event notification", "SSDP Discovery Service"],
["UDP", 5004, "RTP", "Windows Media Services"],
["UDP", 5005, "RTCP", "Windows Media Services"],
["TCP", "5061", "SIP/MTLS", "OCS Access Edge Server Communication"],
["TCP", "5062", "SIP/MTLS", "OCS Access Edge Server Authentication"],
["TCP", 6001, "Information Store", "Exchange Server 2003"],
["TCP", 6002, "Directory Referral", "Exchange Server 2003"],
["TCP", 6004, "DSProxy/NSPI", "Exchange Server 2003"],
["TCP", "8057", "PSOM/MTLS", "OCS Web Conferencing Edge Server"],
["TCP", 42424, "ASP.Net Session State", "ASP.NET State Service"],
["TCP", "50000-59999", "OCS A/V Edge Server", "Used for inbound and outbound media transfer"],
["TCP", 51515, "MOM-Clear", "Microsoft Operations Manager 2000"]
]
  };
