
export const data = {
      Ports: [
["Protocol", "Port", "Application protocol", "System service name"],
["GRE", "n/a", "GRE (IP protocol 47)", "Routing and Remote Access"],
["ESP", "n/a", "IPsec ESP (IP protocol 50)", "Routing and Remote Access"],
["AH", "n/a", "IPsec AH (IP protocol 51)", "Routing and Remote Access"],
["TCP", 7, "Echo", "Simple TCP/IP Services"],
["UDP", 7, "Echo", "Simple TCP/IP Services"],
["TCP", 9, "Discard", "Simple TCP/IP Services"],
["UDP", 9, "Discard", "Simple TCP/IP Services"],
["TCP", 13, "Daytime", "Simple TCP/IP Services"],
["UDP", 13, "Daytime", "Simple TCP/IP Services"],
["TCP", 17, "Quotd", "Simple TCP/IP Services"],
["UDP", 17, "Quotd", "Simple TCP/IP Services"],
["TCP", 19, "Chargen", "Simple TCP/IP Services"],
["UDP", 19, "Chargen", "Simple TCP/IP Services"],
["TCP", 20, "FTP default data", "FTP Publishing Service"],
["TCP", 21, "FTP control", "FTP Publishing Service"],
["TCP", 21, "FTP control", "Application Layer Gateway Service"],
["TCP", 23, "Telnet", "Telnet"],
["TCP", 25, "SMTP", "Simple Mail Transfer Protocol"],
["UDP", 25, "SMTP", "Simple Mail Transfer Protocol"],
["TCP", 25, "SMTP", "Exchange Server"],
["UDP", 25, "SMTP", "Exchange Server"],
["TCP", 42, "WINS Replication", "Windows Internet Name Service"],
["UDP", 42, "WINS Replication", "Windows Internet Name Service"],
["TCP", 53, "DNS", "DNS Server"],
["UDP", 53, "DNS", "DNS Server"],
["TCP", 53, "DNS", "Internet Connection Firewall/Internet Connection Sharing"],
["UDP", 53, "DNS", "Internet Connection Firewall/Internet Connection Sharing"],
["UDP", 67, "DHCP Server", "DHCP Server"],
["UDP", 67, "DHCP Server", "Internet Connection Firewall/Internet Connection Sharing"],
["UDP", 69, "TFTP", "Trivial FTP Daemon Service"],
["TCP", 80, "HTTP", "Windows Media Services"],
["TCP", 80, "HTTP", "World Wide Web Publishing Service"],
["TCP", 80, "HTTP", "SharePoint Portal Server"],
["TCP", 88, "Kerberos", "Kerberos Key Distribution Center"],
["UDP", 88, "Kerberos", "Kerberos Key Distribution Center"],
["TCP", 102, "X.400", "Microsoft Exchange MTA Stacks"],
["TCP", 110, "POP3", "Microsoft POP3 Service"],
["TCP", 110, "POP3", "Exchange Server"],
["TCP", 119, "NNTP", "Network News Transfer Protocol"],
["UDP", 123, "NTP", "Windows Time"],
["UDP", 123, "SNTP", "Windows Time"],
["TCP", 135, "RPC", "Message Queuing"],
["TCP", 135, "RPC", "Remote Procedure Call"],
["TCP", 135, "RPC", "Exchange Server"],
["TCP", 135, "RPC", "Certificate Services"],
["TCP", 135, "RPC", "Cluster Service"],
["TCP", 135, "RPC", "Distributed File System"],
["TCP", 135, "RPC", "Distributed Link Tracking"],
["TCP", 135, "RPC", "Distributed Transaction Coordinator"],
["TCP", 135, "RPC", "Event Log"],
["TCP", 135, "RPC", "Fax Service"],
["TCP", 135, "RPC", "File Replication"],
["TCP", 135, "RPC", "Group Policy"],
["TCP", 135, "RPC", "Local Security Authority"],
["TCP", 135, "RPC", "Remote Storage Notification"],
["TCP", 135, "RPC", "Remote Storage Server"],
["TCP", 135, "RPC", "Systems Management Server 2.0"],
["TCP", 135, "RPC", "Terminal Services Licensing"],
["TCP", 135, "RPC", "Terminal Services Session Directory"],
["UDP", 137, "NetBIOS Name Resolution", "Computer Browser"],
["UDP", 137, "NetBIOS Name Resolution", "Server"],
["UDP", 137, "NetBIOS Name Resolution", "Windows Internet Name Service"],
["UDP", 137, "NetBIOS Name Resolution", "Net Logon"],
["UDP", 137, "NetBIOS Name Resolution", "Systems Management Server 2.0"],
["UDP", 138, "NetBIOS Datagram Service", "Computer Browser"],
["UDP", 138, "NetBIOS Datagram Service", "Messenger"],
["UDP", 138, "NetBIOS Datagram Service", "Server"],
["UDP", 138, "NetBIOS Datagram Service", "Net Logon"],
["UDP", 138, "NetBIOS Datagram Service", "Distributed File System"],
["UDP", 138, "NetBIOS Datagram Service", "Systems Management Server 2.0"],
["UDP", 138, "NetBIOS Datagram Service", "License Logging Service"],
["TCP", 139, "NetBIOS Session Service", "Computer Browser"],
["TCP", 139, "NetBIOS Session Service", "Fax Service"],
["TCP", 139, "NetBIOS Session Service", "Performance Logs and Alerts"],
["TCP", 139, "NetBIOS Session Service", "Print Spooler"],
["TCP", 139, "NetBIOS Session Service", "Server"],
["TCP", 139, "NetBIOS Session Service", "Net Logon"],
["TCP", 139, "NetBIOS Session Service", "Remote Procedure Call Locator"],
["TCP", 139, "NetBIOS Session Service", "Distributed File System"],
["TCP", 139, "NetBIOS Session Service", "Systems Management Server 2.0"],
["TCP", 139, "NetBIOS Session Service", "License Logging Service"],
["TCP", 143, "IMAP", "Exchange Server"],
["UDP", 161, "SNMP", "SNMP Service"],
["UDP", 162, "SNMP Traps Outbound", "SNMP Trap Service"],
["TCP", 389, "LDAP Server", "Local Security Authority"],
["UDP", 389, "LDAP Server", "Local Security Authority"],
["TCP", 389, "LDAP Server", "Distributed File System"],
["UDP", 389, "LDAP Server", "Distributed File System"],
["TCP", 443, "HTTPS", "HTTP SSL"],
["TCP", 443, "HTTPS", "World Wide Web Publishing Service"],
["TCP", 443, "HTTPS", "SharePoint Portal Server"],
["TCP", 443, "RPC over HTTPS", "Exchange Server 2003"],
["TCP", 445, "SMB", "Fax Service"],
["TCP", 445, "SMB", "Print Spooler"],
["TCP", 445, "SMB", "Server"],
["TCP", 445, "SMB", "Remote Procedure Call Locator"],
["TCP", 445, "SMB", "Distributed File System"],
["TCP", 445, "SMB", "License Logging Service"],
["TCP", 445, "SMB", "Net Logon"],
["TCP", 464, "Kerberos Password V5", "Net Logon"],
["UDP", 500, "IPsec ISAKMP", "Local Security Authority"],
["TCP", 515, "LPD", "TCP/IP Print Server"],
["TCP", 548, "File Server for Macintosh", "File Server for Macintosh"],
["TCP", 554, "RTSP", "Windows Media Services"],
["TCP", 563, "NNTP over SSL", "Network News Transfer Protocol"],
["TCP", 593, "RPC over HTTPS endpoint mapper", "Remote Procedure Call"],
["TCP", 593, "RPC over HTTPS", "Exchange Server"],
["TCP", 636, "LDAP SSL", "Local Security Authority"],
["UDP", 636, "LDAP SSL", "Local Security Authority"],
["TCP", 993, "IMAP over SSL", "Exchange Server"],
["TCP", 995, "POP3 over SSL", "Exchange Server"],
["TCP", 1067, "Installation Bootstrap Service", "Installation Bootstrap protocol server"],
["TCP", 1068, "Installation Bootstrap Service", "Installation Bootstrap protocol client"],
["TCP", 1270, "MOM-Encrypted", "Microsoft Operations Manager 2000"],
["TCP", 1433, "SQL over TCP", "Microsoft SQL Server"],
["TCP", 1433, "SQL over TCP", "MSSQL$UDDI"],
["UDP", 1434, "SQL Probe", "Microsoft SQL Server"],
["UDP", 1434, "SQL Probe", "MSSQL$UDDI"],
["TCP", "1512", "WINS", "Windows Internet Name Service"],
["UDP", "1512", "WINS", "Windows Internet Name Service"],
["UDP", 1645, "Legacy RADIUS", "Internet Authentication Service"],
["UDP", 1646, "Legacy RADIUS", "Internet Authentication Service"],
["UDP", 1701, "L2TP", "Routing and Remote Access"],
["TCP", 1723, "PPTP", "Routing and Remote Access"],
["TCP", 1755, "MMS", "Windows Media Services"],
["UDP", 1755, "MMS", "Windows Media Services"],
["TCP", 1801, "MSMQ", "Message Queuing"],
["UDP", 1801, "MSMQ", "Message Queuing"],
["UDP", 1812, "RADIUS Authentication", "Internet Authentication Service"],
["UDP", 1813, "RADIUS Accounting", "Internet Authentication Service"],
["TCP", "1863", "Microsoft Messenger Protocol", "MSN Messenger"],
["UDP", "1863", "Microsoft Messenger Protocol", "MSN Messenger"],
["UDP", 1900, "SSDP", "SSDP Discovery Service"],
["TCP", 2101, "MSMQ-DCs", "Message Queuing"],
["TCP", 2103, "MSMQ-RPC", "Message Queuing"],
["TCP", 2105, "MSMQ-RPC", "Message Queuing"],
["TCP", 2107, "MSMQ-Mgmt", "Message Queuing"],
["TCP", "2383", "OLAP Services 9.0", "SQL Server: Downlevel OLAP Client Support (SQL 2005)"],
["TCP", 2393, "OLAP Services 7.0 / 8.0", "SQL Server: Downlevel OLAP Client Support"],
["TCP", 2394, "OLAP Services 7.0 / 8.0", "SQL Server: Downlevel OLAP Client Support"],
["UDP", 2460, "MS Theater", "Windows Media Services"],
["UDP", 2535, "MADCAP", "DHCP Server"],
["TCP", 2701, "SMS Remote Control (control)", "SMS Remote Control Agent"],
["UDP", 2701, "SMS Remote Control (control)", "SMS Remote Control Agent"],
["TCP", 2702, "SMS Remote Control (data)", "SMS Remote Control Agent"],
["UDP", 2702, "SMS Remote Control (data)", "SMS Remote Control Agent"],
["TCP", 2703, "SMS Remote Chat", "SMS Remote Control Agent"],
["UPD", 2703, "SMS Remote Chat", "SMS Remote Control Agent"],
["TCP", 2704, "SMS Remote File Transfer", "SMS Remote Control Agent"],
["UDP", 2704, "SMS Remote File Transfer", "SMS Remote Control Agent"],
["TCP", 2725, "SQL Analysis Services", "SQL Analysis Server"],
["TCP", 2869, "UPNP", "Universal Plug and Play Device Host"],
["TCP", 2869, "SSDP event notification", "SSDP Discovery Service"],
["TCP", 3268, "Global Catalog Server", "Local Security Authority"],
["TCP", 3269, "Global Catalog Server over SSL", "Local Security Authority over SSL"],
["UDP", 3343, "Cluster Services", "Cluster Service"],
["TCP", 3389, "Terminal Services", "NetMeeting Remote Desktop Sharing"],
["TCP", 3389, "Terminal Services", "Terminal Services"],
["UDP", "3478", "STUN", "OCS A/V Edge Server for STUN Communications"],
["UDP", 3527, "MSMQ-Ping", "Message Queuing"],
["UDP", 4011, "BINL", "Remote Installation"],
["UDP", 4500, "NAT-T", "Local Security Authority"],
["TCP", 5000, "SSDP legacy event notification", "SSDP Discovery Service"],
["UDP", 5004, "RTP", "Windows Media Services"],
["UDP", 5005, "RTCP", "Windows Media Services"],
["TCP", "5061", "SIP/MTLS", "OCS Access Edge Server Communication"],
["TCP", "5062", "SIP/MTLS", "OCS Access Edge Server Authentication"],
["TCP", 6001, "Information Store", "Exchange Server 2003"],
["TCP", 6002, "Directory Referral", "Exchange Server 2003"],
["TCP", 6004, "DSProxy/NSPI", "Exchange Server 2003"],
["TCP", "8057", "PSOM/MTLS", "OCS Web Conferencing Edge Server"],
["TCP", 42424, "ASP.Net Session State", "ASP.NET State Service"],
["TCP", "50000-59999", "OCS A/V Edge Server", "Used for inbound and outbound media transfer"],
["TCP", 51515, "MOM-Clear", "Microsoft Operations Manager 2000"]
],
ACAS_Plugins: [
["Family", "Tenable App", "Plugin Type", "Plugin ID", "Description", "Remarks"],
["Troubleshooting", "Nessus", "Successful Login (Windows)", 10394, "Microsoft Windows SMB Log In Possible"],
["Troubleshooting", "Nessus", "Successful Login (Windows)", 10400, "Microsoft Windows SMB Registry Remotely Accessible"],
["Troubleshooting", "Nessus", "Successful Login (Windows)", 20811, "Microsoft Windows Installed Software Enumeration (credentialed check)"],
["Troubleshooting", "Nessus", "Successful Login (Windows)", 24269, "WMI (Windows Management Instrumentation) Available"],
["Troubleshooting", "Nessus", "Successful Login (Linux)", 12634, "Authenticated Check: OS Name and Installed Package Enumeration"],
["Troubleshooting", "Nessus", "Successful Login (Linux)", 22869, "Software Enumeration (SSH)"],
["Troubleshooting", "Nessus", "Successful Login (Linux)", 27576, "Firewall Detection"],
["Troubleshooting", "Nessus", "Successful Login (Linux)", 110095, "Target Credential Issues by Authentication Protocol - No Issues Found"],
["Troubleshooting", "Nessus", "Successful Login (Win & Lin)", 141118, "Target Credential Status by Authentication Protocol - Valid Credentials Provided"],
["Troubleshooting", "Nessus", "Successful Login (Win & Lin)", 122502, "Integration Credential Status by Authentication Protocol - Valid Credentials Provided"],
["Troubleshooting", "Nessus", "Successful Login (Win & Lin)", 110095, "Target Credential Issues by Authentication Protocol - No Issues Found"],
["Troubleshooting", "Nessus", "Login Failure (Win & Lin)", 110723, "Target Credential Status by Authentication Protocol - No Credentials Provided"],
["Troubleshooting", "Nessus", "Login Failure (Win & Lin)", 104410, "Target Credential Status by Authentication Protocol - Failure for Provided Credentials"],
["Troubleshooting", "Nessus", "Login Failure (Win & Lin)", 110385, "Target Credential Issues by Authentication Protocol - Insufficient Privilege "],
["Troubleshooting", "Nessus", "Login Failure (Win & Lin)", 117885, "Target Credential Issues by Authentication Protocol - Intermittent Authentication Failure"],
["Troubleshooting", "Nessus", "Login Failure (Win & Lin)", 122503, "Integration Credential Status by Authentication Protocol -Failure for Provided Credentials"],
["Troubleshooting", "Nessus", "Login Failure (Win & Lin)", 21745, "Authentication Failure - Local Checks Not Run"],
["Troubleshooting", "Nessus", "Login Failure (Win & Lin)", 24786, "Nessus Windows Scan Not Performed with Admin Privileges"],
["Troubleshooting", "Nessus", "Login Failure (Win & Lin)", 10428, "Microsoft Windows SMB Registry Not Fully Accessible Detection"],
["Troubleshooting", "Nessus", "Login Failure (Win & Lin)", 26917, "Microsoft Windows SMB Registry: Nessus Cannot Access the Windows Registry"],
["Troubleshooting", "Nessus", "Login Failure (Win & Lin)", 91822, "Database Authentication Failure(s) for Provided Credentials"],
["Troubleshooting", "Nessus", "Login Failure (Win & Lin)", 11149, "HTTP Login Page"],
["Troubleshooting", "Nessus", "Login Failure (Win & Lin)", 21745, "OS Security Patch Assessment Failed", "Note: This indicates Tenable Nessus is unable to connect to the\nsystem, usually for one of the following reasons:\nl Nessus is unable to connect due to network issues\nl A network or host-based firewall is blocking the\nconnection attempts\nl Due to network latency, a timeout is reached before\nthe connection occurs\nl The user that started the scan does not have\npermission to scan the given host and/or port.\nNessus users have no restrictions by default, so this\nonly happens if an administrator puts a restriction\non a user.\nl Nessus has too many open sockets during a scan. If\nthis happens the nessusd.dump or\nnessusd.messages indicate the error."],
["Troubleshooting", "Nessus", "Nessus Scan Information (All Scans)", 19506, "Nessus Scan Information (Credentialed Scan - Credentialed Text)", "Tenable Security Center Filter: Vulnerability Text\nContains “Credentialed checks : yes”\nTenable Vulnerability Management Filter: Plugin Output\nContains “Credentialed checks : yes”"],
["Troubleshooting", "Nessus", "Nessus Scan Information (All Scans)", 112154, "Nessus Launched Plugin List", "Note: To use this plugin, you must enable the debug setting. For\nmore information, see Advanced Settings in the Tenable\nNessus User Guide."],
["Troubleshooting", "Nessus", "Other", 10919, "Open Port Re-Check"],
["Troubleshooting", "Nessus", "Other", 35453, "Microsoft Windows Update Reboot Required"],
["Troubleshooting", "Nessus", "Other", 35703, "SMB Registry: Start the Registry Service During the Scan"],
["Troubleshooting", "Nessus", "Other", 35704, "SMB Registry: Stop the Registry Service After the Scan"],
["Troubleshooting", "Nessus", "Other", 35705, "SMB Registry: Starting the Registry Service during the Scan\nFailed"],
["Troubleshooting", "Nessus", "Other", 35706, "SMB Registry : Stopping the Registry Service after the Scan Failed"],
["Troubleshooting", "Nessus", "Other", 84239, "Debugging Log Report"],
["Useful", "Nessus", "Vulnerabilities to Look For", 26921, "Windows Service Pack Out-of-Date"],
["Useful", "Nessus", "Vulnerabilities to Look For", 33851, "Network Daemons Not Managed by the Package System"],
["Useful", "Nessus", "Vulnerabilities to Look For", 59275, "Malicious Process Detection"],
["Useful", "Nessus", "Agent Plugins", 100574, "Tenable Windows Nessus Agent Installed"],
["Useful", "Nessus", "Agent Plugins", 110230, "Tenable Nessus Agent Installed (Linux)"],
["Useful", "Nessus", "Agent Plugins", 110231, "Tenable Nessus Agent Installed (macOS"],
["Useful", "Nessus", "System Information", 10107, "HTTP Server Type and Version"],
["Useful", "Nessus", "System Information", 10150, "Windows NetBIOS / SMB Remote Host Information\nDisclosure"],
["Useful", "Nessus", "System Information", 10395, "Microsoft Windows SMB Shares Enumeration"],
["Useful", "Nessus", "System Information", 10396, "Microsoft Windows SMB Shares Access"],
["Useful", "Nessus", "System Information", 11936, "OS Identification"],
["Useful", "Nessus", "System Information", 12053, "Host Fully Qualified Domain Name (FQDN) Resolution"],
["Useful", "Nessus", "System Information", 20811, "Microsoft Windows Installed Software Enumeration (Credentialed Check)"],
["Useful", "Nessus", "System Information", 24272, "Network Interfaces Enumeration (WMI)"],
["Useful", "Nessus", "System Information", 25203, "Enumerate IPv4 Interfaces via SSH"],
["Useful", "Nessus", "System Information", 25221, "Remote Listeners Enumeration (Linux / AIX)"],
["Useful", "Nessus", "System Information", 34252, "Microsoft Windows Remote Listeners Enumeration (WMI)"],
["Useful", "Nessus", "System Information", 35453, "Microsoft Windows Update Reboot Required"],
["Useful", "Nessus", "System Information", 55472, "Device Hostname"],
["Useful", "Nessus", "System Information", 64582, "Netstat Connection Information"],
["Useful", "Nessus", "System Information", 66334, "Patch Report"],
["Useful", "Nessus", "System Information", 93561, "Docker Service Detection"],
["Useful", "Nessus", "System Information", 112154, "Nessus Launched Plugin List", "Note: To use this plugin, you must enable the debug setting.\nFor more information, see Advanced Settings in the Tenable\nNessus User Guide."],
["Discovery", "ACAS", "General", 45590, "Common Platform Enumeration (CPE)", "Note: In the Tenable Nessus interface, enable the Hide results from plugins initiated as a dependency\noption to ensure IPs do not count toward your license if they are scanned with one of the following plugins.\nFor more information, see Report Scan Settings in the Tenable Nessus User Guide."],
["Discovery", "ACAS", "General", 54615, "Device Type", "Note: In the Tenable Nessus interface, enable the Hide results from plugins initiated as a dependency\noption to ensure IPs do not count toward your license if they are scanned with one of the following plugins.\nFor more information, see Report Scan Settings in the Tenable Nessus User Guide."],
["Discovery", "ACAS", "General", 12053, "Host Fully Qualified Domain Name (FQDN) Resolution ", "Note: In the Tenable Nessus interface, enable the Hide results from plugins initiated as a dependency\noption to ensure IPs do not count toward your license if they are scanned with one of the following plugins.\nFor more information, see Report Scan Settings in the Tenable Nessus User Guide."],
["Discovery", "ACAS", "General", 11936, "OS Identification", "Note: In the Tenable Nessus interface, enable the Hide results from plugins initiated as a dependency\noption to ensure IPs do not count toward your license if they are scanned with one of the following plugins.\nFor more information, see Report Scan Settings in the Tenable Nessus User Guide."],
["Discovery", "ACAS", "General", 10287, "Traceroute Information", "Note: In the Tenable Nessus interface, enable the Hide results from plugins initiated as a dependency\noption to ensure IPs do not count toward your license if they are scanned with one of the following plugins.\nFor more information, see Report Scan Settings in the Tenable Nessus User Guide."],
["Discovery", "ACAS", "Service Detection", 22964, "Service Detection", "Note: In the Tenable Nessus interface, enable the Hide results from plugins initiated as a dependency\noption to ensure IPs do not count toward your license if they are scanned with one of the following plugins.\nFor more information, see Report Scan Settings in the Tenable Nessus User Guide."],
["Discovery", "ACAS", "Settings", 11933, "Do not Scan Printers", "Note: In the Tenable Nessus interface, enable the Hide results from plugins initiated as a dependency\noption to ensure IPs do not count toward your license if they are scanned with one of the following plugins.\nFor more information, see Report Scan Settings in the Tenable Nessus User Guide."],
["Discovery", "ACAS", "Settings", 87413, "Host Tagging", "Note: In the Tenable Nessus interface, enable the Hide results from plugins initiated as a dependency\noption to ensure IPs do not count toward your license if they are scanned with one of the following plugins.\nFor more information, see Report Scan Settings in the Tenable Nessus User Guide."],
["Discovery", "ACAS", "Settings", 33812, "Port Scanners Settings", "Note: In the Tenable Nessus interface, enable the Hide results from plugins initiated as a dependency\noption to ensure IPs do not count toward your license if they are scanned with one of the following plugins.\nFor more information, see Report Scan Settings in the Tenable Nessus User Guide."],
["Discovery", "ACAS", "Settings", 33813, "Port Scanner Dependency", "Note: In the Tenable Nessus interface, enable the Hide results from plugins initiated as a dependency\noption to ensure IPs do not count toward your license if they are scanned with one of the following plugins.\nFor more information, see Report Scan Settings in the Tenable Nessus User Guide."],
["Discovery", "ACAS", "Settings", 112154, "Nessus Launches Plugin List", "Note: To use this plugin, you must enable the debug\nsetting. For more information, see Advanced Settings in the\nTenable Nessus User Guide"],
["Configurations Settings", "ACAS", "Port Scanners", 10180, "Ping the Remote Host"],
["Configurations Settings", "ACAS", "Port Scanners", 10335, "Nessus TCP Scanner"],
["Configurations Settings", "ACAS", "Port Scanners", 11219, "Nessus SYN Scanner"],
["Configurations Settings", "ACAS", "Port Scanners", 14272, "Netstat Portscanner (SSH)"],
["Configurations Settings", "ACAS", "Port Scanners", 14274, "Nessus SNMP Scanner"],
["Configurations Settings", "ACAS", "Port Scanners", 34220, "Netstat Portscanner (WMI)"],
["Configurations Settings", "ACAS", "Port Scanners", 34277, "Nessus UDP Scanner"],
["N/A", "NNM", "N/A", 0, "Open Port"],
["N/A", "NNM", "N/A", 12, "Host TTL Discovered"],
["N/A", "NNM", "N/A", 18, "Generic Protocol Detection"],
["N/A", "NNM", "N/A", 19, "VLAN ID Detection"],
["N/A", "NNM", "N/A", 20, "Generic IPv6 Tunnel Traffic Detection"],
["N/A", "NNM", "N/A", 113, "VXLAN ID Detection"],
["N/A", "NNM", "N/A", 132, "Host Attribute Enumeration"]
]
  };