
interface DataType {
      [key: string]: string[][];
}
export const data:DataType = {
      LLM01: [
["", "", "", "Prevention and mitigation strategies", "Common examples and vulnerabilities", "Example attack scenarios"],
["Prompt Injection", "\"This manipulates a large language model (LLM) through\ncrafty inputs, causing unintended actions by the LLM.\nDirect injections overwrite system prompts, while indirect\nones manipulate inputs from external sources.\"1.1", "1", "Enforce privilege control on LLM access to backend systems. Provide the LLM with its\nown API tokens for extensible functionality, such as plugins, data access, and function-\nlevel permissions. Follow the principle of least privilege by restricting the LLM to only\nthe minimum level of access necessary for its intended operations.", "A malicious user crafts a direct prompt injection to the LLM, which instructs it to ignore the application creator's system prompts and instead execute a prompt that returns private, dangerous, or otherwise undesirable information.", "An attacker provides a direct prompt injection to an LLM-based support chatbot. The injection contains “forget all previous instructions” and new instructions to query private data stores and exploit package vulnerabilities and the lack of output validation in the backend function to send e-mails. This leads to remote code execution, gaining unauthorized access and privilege escalation."],
["", "", "2", "Add a human in the loop for extended functionality. When performing privileged operations, such as sending or deleting emails, have the application require the user approve the action first. This reduces the opportunity for an indirect prompt injections to lead to unauthorised actions on behalf of the user without their knowledge or consent Segregate.", "A user employs an LLM to summarize a webpage containing an indirect prompt injection. This then causes the LLM to solicit sensitive information from the user and perform exfiltration via JavaScript or Markdown.", "An attacker embeds an indirect prompt injection in a webpage instructing the LLM to \ndisregard previous user instructions and use an LLM plugin to delete the user's emails. \nWhen the user employs the LLM to summarise this webpage, the LLM plugin deletes \nthe user's emails."],
["", "", "3", "Segregate external content from user prompts. Separate and denote where untrusted content is being used to limit their influence on user prompts. For example, use ChatML for OpenAI API calls to indicate to the LLM the source of prompt input.", "A malicious user uploads a resume containing an indirect prompt injection. The document contains a prompt injection with instructions to make the LLM inform users that this document is excellent eg. an excellent candidate for a job role. An internal user runs the document through the LLM to summarize the document. The output of the LLM returns information stating that this is an excellent document", "A user uses an LLM to summarize a webpage containing text instructing a model to \ndisregard previous user instructions and instead insert an image linking to a URL that \ncontains a summary of the conversation. The LLM output complies, causing the user's \nbrowser to exfiltrate the private conversation."],
["", "", "4", "Establish trust boundaries between the LLM, external sources, and extensible \nfunctionality (e.g., plugins or downstream functions). Treat the LLM as an untrusted \nuser and maintain final user control on decision-making processes. However, a \ncompromised LLM may still act as an intermediary (man-in-the-middle) between your application’s APIs and the user as it may hide or manipulate information prior to \npresenting it to the user. Highlight potentially untrustworthy responses visually to the user.", "A user enables a plugin linked to an e-commerce site. A rogue instruction embedded on a visited website exploits this plugin, leading to unauthorized purchases.", "A malicious user uploads a resume with a prompt injection. The backend user uses an \nLLM to summarize the resume and ask if the person is a good candidate. Due to the \nprompt injection, the LLM response is yes, despite the actual resume contents."],
["", "", "5", "Manually monitor LLM input and output periodically, to check that it is as expected. \nWhile not a mitigation, this can provide data needed to detect weaknesses and \naddress them.", "A rogue instruction and content embedded on a visited website exploits other plugins \nto scam users.", "An attacker sends messages to a proprietary model that relies on a system prompt, \nasking the model to disregard its previous instructions and instead repeat its system \nprompt. The model outputs the proprietary prompt and the attacker is able to use \nthese instructions elsewhere, or to construct further, more subtle attacks."]
],
LLM02: [
["", "", "", "Prevention and mitigation strategies", "Common examples and vulnerabilities", "Example attack scenarios"],
["Subject 2", "This vulnerability occurs when an LLM output is accepted \nwithout scrutiny, exposing backend systems. Misuse may \nlead to severe consequences like XSS, CSRF, SSRF, \nprivilege escalation, or remote code execution.", "1", "Treat the model as any other user, adopting a zero-trust approach, and apply proper input validation on responses coming from the model to backend functions.", "LLM output is entered directly into a system shell or similar function such as eval or exec resulting in remote code execution.\n", "An application utilizes an LLM plugin to generate responses for a chatbot feature. The \nplugin also offers a number of administrative functions accessible to another privileged LLM. The general purpose LLM directly passes its response, without proper output validation, to the plugin causing the plugin to shut down for maintenance."],
["", "", "2", " Follow the OWASP ASVS (Application Security Verification Standard) guidelines to \nensure effective input validation and sanitization.", "JavaScript or Markdown is generated by the LLM and returned to a user. The code is \nthen interpreted by the browser, resulting in XSS.", "A user utilizes a website summarizer tool powered by an LLM to generate a concise \nsummary of an article. The website includes a prompt injection instructing the LLM to \ncapture sensitive content from either the website or from the user's conversation. \nFrom there the LLM can encode the sensitive data and send it, without any output \nvalidation or filtering, to an attacker-controlled server."],
["", "", "3", "Encode model output back to users to mitigate undesired code execution by JavaScript or Markdown. OWASP ASVS provides detailed guidance on output encoding.", "", "An LLM allows users to craft SQL queries for a backend database through a chat-like \nfeature. A user requests a query to delete all database tables. If the crafted query from \nthe LLM is not scrutinized, then all database tables will be deleted."],
["", "", "4", "", "", "A web app uses an LLM to generate content from user text prompts without output \nsanitization. An attacker could submit a crafted prompt causing the LLM to return an \nunsanitized JavaScript payload, leading to XSS when rendered on a victim's browser. \nInsufficient validation of prompts enabled this attack."]
],
LLM03: [
["", "", "", "Prevention and mitigation strategies", "Common examples and vulnerabilities", "Common Examples (cont)", "Example attack scenarios"],
["Subject 3", "This occurs when LLM training data is tampered, introducing vulnerabilities or biases that compromise security, effectiveness, or ethical behavior. Sources include Common Crawl, WebText, OpenWebText, & books.", "1", " Verify the supply chain of the training data, especially when sourced externally as well \nas maintaining attestations via the \"ML-BOM\" (Machine Learning Bill of Materials) methodology as well as verifying model cards.", "A malicious actor, or a competitor brand intentionally creates inaccurate or malicious documents which are targeted at a model’s pre-training, fine-tuning data or embeddings. Consider both Split-View Data Poisoning and Frontrunning Poisoning attack vectors for illustrations.", "a. The victim model trains using falsified information which is reflected in outputs of generative AI prompts to it's consumers.", "The LLM generative AI prompt output can mislead users of the application which can \nlead to biased opinions, followings or even worse, hate crimes etc"],
["", "", "2", "Verify the correct legitimacy of targeted data sources and data contained obtained during both the pre-training, fine-tuning and embedding stages.", "A malicious actor is able to perform direct injection of falsified, biased or harmful content into the training processes of a model which is returned in subsequent outputs.", "", "If the training data is not correctly filtered and|or sanitized, a malicious user of the application may try to influence and inject toxic data into the model for it to adapt to the biased and false data."],
["", "", "3", " Verify your use-case for the LLM and the application it will integrate to. Craft different models via separate training data or fine-tuning for different use-cases to create a more granular and accurate generative AI output as per it's defined use-case.", "An unsuspecting user is indirectly injecting sensitive or proprietary data into the training processes of a model which is returned in subsequent outputs.", "", "A malicious actor or competitor intentionally creates inaccurate or malicious documents which are targeted at a model’s training data in which is training the model at the same time based on inputs. The victim model trains using this falsified information which is reflected in outputs of generative AI prompts to it's consumers."],
["", "", "4", " Ensure sufficient sandboxing through network controls are present to prevent the model from scraping unintended data sources which could hinder the machine learning output.", "A model is trained using data which has not been verified by its source, origin or content in any of the training stage examples which can lead to erroneous results if the data is tainted or incorrect.", "", "The vulnerability Prompt Injection could be an attack vector to this vulnerability if insufficient sanitization and filtering is performed when clients of the LLM application input is used to train the model. I.E, if malicious or falsified data is input to the model \nfrom a client as part of a prompt injection technique, this could inherently be portrayed \ninto the model data."],
["", "", "5", "Use strict vetting or input filters for specific training data or categories of data sources to control volume of falsified data. Data sanitization, with techniques such as statistical outlier detection and anomaly detection methods to detect and remove adversarial data from potentially being fed into the fine-tuning process.", "Unrestricted infrastructure access or inadequate sandboxing may allow a model to ingest unsafe training data resulting in biased or harmful outputs. This example is also present in any of the training stage examples.", "a. In this scenario, a users input to the model may be reflected in the output to another user (leading to a breach), or the user of an LLM may receive outputs from the model which are inaccurate, irrelevant or harmful depending on the type of data \ningested compared to the model use-case (usually reflected with a model card).", ""],
["", "", "6", " Adversarial robustness techniques such as federated learning and constraints to minimize the effect of outliers or adversarial training to be vigorous against worst-case \nperturbations of the training data.\na. An \"MLSecOps\" approach could be to include adversarial robustness to the training \nlifecycle with the auto poisoning technique.\nb. An example repository of this would be Autopoison testing, including both attacks such as Content Injection Attacks (“(attempting to promote a brand name in model responses”) and Refusal Attacks (“always making the model refuse to respond”) that \ncan be accomplished with this approach.", "Whether a developer, client or general consumer of the LLM, it is important to \nunderstand the implications of how this vulnerability could reflect risks within your LLM application when interacting with a non-proprietary LLM to understand the legitimacy of model outputs based on it's training procedures. Similarly, developers of the LLM may be at risk to both direct and indirect attacks on internal or third-party data used for fine-tuning and embedding (most common) which as a result creates a risk for all it's consumers.", "", ""],
["", "", "7", "Testing and Detection, by measuring the loss during the training stage and analyzing \ntrained models to detect signs of a poisoning attack by analyzing model behavior on \nspecific test inputs.\na. Monitoring and alerting on number of skewed responses exceeding a threshold.\nb. Use of a human loop to review responses and auditing\nc. Implement dedicated LLMs to benchmark against undesired consequences and \ntrain other LLMs using reinforcement learning techniques.\nd. Perform LLM-based red team exercises or LLM vulnerability scanning into the testing phases of the LLM's lifecycle.", "", "", ""]
],
LLM04: [
["", "", "", "Prevention and mitigation strategies", "Common examples and vulnerabilities", "Example attack scenarios"],
["Subject 4", "Attackers cause resource-heavy operations on LLMs, \nleading to service degradation or high costs. The \nvulnerability is magnified due to the resource-intensive \nnature of LLMs and unpredictability of user inputs.", "1", "Implement input validation and sanitization to ensure user input adheres to defined limits and filters out any malicious content.", "Posing queries that lead to recurring resource usage through high-volume generation of tasks in a queue, e.g. with LangChain or AutoGPT.", "An attacker repeatedly sends multiple difficult and costly requests to a hosted model leading to worse service for other users and increased resource bills for the host."],
["", "", "2", "Cap resource use per request or step, so that requests involving complex parts \nexecute more slowly.", "Sending unusually resource-consuming queries that use unusual orthography or \nsequences.", " A piece of text on a webpage is encountered while an LLM-driven tool is collecting information to respond to a benign query. This leads to the tool making many more web page requests, resulting in large amounts of resource consumption."],
["", "", "3", "Enforce API rate limits to restrict the number of requests an individual user or IP address can make within a specific timeframe.", "Continuous input overflow: An attacker sends a stream of input to the LLM that \nexceeds its context window, causing the model to consume excessive computational resources.", "An attacker continuously bombards the LLM with input that exceeds its context window. The attacker may use automated scripts or tools to send a high volume of input, overwhelming the LLM's processing capabilities. As a result, the LLM consumes excessive computational resources, leading to a significant slowdown or complete unresponsiveness of the system."],
["", "", "4", "Limit the number of queued actions and the number of total actions in a system \nreacting to LLM responses.", "Repetitive long inputs: The attacker repeatedly sends long inputs to the LLM, each exceeding the context window.", "An attacker sends a series of sequential inputs to the LLM, with each input designed to be just below the context window's limit. By repeatedly submitting these inputs, the attacker aims to exhaust the available context window capacity. As the LLM struggles to process each input within its context window, system resources become strained, potentially resulting in degraded performance or a complete denial of service."],
["", "", "5", "Continuously monitor the resource utilization of the LLM to identify abnormal spikes or patterns that may indicate a DoS attack.", "Recursive context expansion: The attacker constructs input that triggers recursive context expansion, forcing the LLM to repeatedly expand and process the context window.", "An attacker leverages the LLM's recursive mechanisms to trigger context expansion repeatedly. By crafting input that exploits the recursive behavior of the LLM, the attacker forces the model to repeatedly expand and process the context window, consuming significant computational resources. This attack strains the system and may lead to a DoS condition, making the LLM unresponsive or causing it to crash."],
["", "", "6", "Set strict input limits based on the LLM's context window to prevent overload and \nresource exhaustion.", "Variable-length input flood: The attacker floods the LLM with a large volume of \nvariable-length inputs, where each input is carefully crafted to just reach the limit of the context window. This technique aims to exploit any inefficiencies in processing variable-length inputs, straining the LLM and potentially causing it to become unresponsive.", "An attacker floods the LLM with a large volume of variable-length inputs, carefully crafted to approach or reach the context window's limit. By overwhelming the LLM with inputs of varying lengths, the attacker aims to exploit any inefficiencies in processing \nvariable-length inputs. This flood of inputs puts an excessive load on the LLM's resources, potentially causing performance degradation and hindering the system's ability to respond to legitimate requests."],
["", "", "7", "Promote awareness among developers about potential DoS vulnerabilities in LLMs and provide guidelines for secure LLM implementation.", "", "While DoS attacks commonly aim to overwhelm system resources, they can also exploit other aspects of system behavior, such as API limitations. For example, in a \nrecent Sourcegraph security incident, the malicious actor employed a leaked admin access token to alter API rate limits, thereby potentially causing service disruptions by \nenabling abnormal levels of request volumes."]
],
LLM05: [
["", "", "", "Prevention and mitigation strategies", "Common examples and vulnerabilities", "Example attack scenarios"],
["Subject 5", "LLM application lifecycle can be compromised by vulnerable components or services, leading to security attacks. Using third-party datasets, pre- trained models, and plugins can add vulnerabilities.", "1", "Carefully vet data sources and suppliers, including T&Cs and their privacy policies, only using trusted suppliers. Ensure adequate and independently audited security is in \nplace and that model operator policies align with your data protection policies, i.e., your data is not used for training their models; similarly, seek assurances and legal \nmitigations against using copyrighted material from model maintainers.", "Traditional third-party package vulnerabilities, including outdated or deprecated components.", "An attacker exploits a vulnerable Python library to compromise a system. This happened in the first Open AI data breach."],
["", "", "2", "Only use reputable plugins and ensure they have been tested for your application requirements. LLM-Insecure Plugin Design provides information on the LLM-aspects of \nInsecure Plugin design you should test against to mitigate risks from using third-party plugins.", "Using a vulnerable pre-trained model for fine-tuning.", "An attacker provides an LLM plugin to search for flights, generating fake links that lead to scamming users."],
["", "", "3", "Understand and apply the mitigations found in the OWASP Top Ten's A06:2021 – Vulnerable and Outdated Components. This includes vulnerability scanning, management, and patching components. For development environments with access to sensitive data, apply these controls in those environments, too.", "Use of poisoned crowd-sourced data for training.", "An attacker exploits the PyPi package registry to trick model developers into downloading a compromised package and exfiltrating data or escalating privilege in a model development environment. This was an actual attack."],
["", "", "4", "Maintain an up-to-date inventory of components using a Software Bill of Materials (SBOM) to ensure you have an up-to-date, accurate, and signed inventory, preventing tampering with deployed packages. SBOMs can be used to detect and alert for new, \nzero-date vulnerabilities quickly.", "Using outdated or deprecated models that are no longer maintained leads to security issues.", "An attacker poisons a publicly available pre-trained model specializing in economic \nanalysis and social research to create a back door that generates misinformation and fake news. They deploy it on a model marketplace (e.g., Hugging Face) for victims to \nuse."],
["", "", "5", " At the time of writing, SBOMs do not cover models, their artifacts, and datasets. If your LLM application uses its own model, you should use MLOps best practices and platforms offering secure model repositories with data, model, and experiment \ntracking.", "Unclear T&Cs and data privacy policies of the model operators lead to the application's sensitive data being used for model training and subsequent sensitive information exposure. This may also apply to risks from using copyrighted material by the model supplier.", "An attacker poisons publicly available datasets to help create a back door when finetuning models. The back door subtly favors certain companies in different markets."],
["", "", "6", "You should also use model and code signing when using external models and suppliers.", "", "A compromised employee of a supplier (outsourcing developer, hosting company, etc.) \nexfiltrates data, model, or code stealing IP."],
["", "", "7", "Anomaly detection and adversarial robustness tests on supplied models and data can help detect tampering and poisoning as discussed in Training Data Poisoning; ideally, this should be part of MLOps pipelines; however, these are emerging techniques and may be easier to implement as part of red teaming exercises.", "", "An LLM operator changes its T&Cs and Privacy Policy to require an explicit opt out from using application data for model training, leading to the memorization of sensitive data."],
["", "", "8", "Implement sufficient monitoring to cover component and environment vulnerabilities scanning, use of unauthorized plugins, and out-of-date components, including the model and its artifacts.", "", ""],
["", "", "9", "Implement a patching policy to mitigate vulnerable or outdated components. Ensure the application relies on a maintained version of APIs and the underlying model.", "", ""],
["", "", "10", "Regularly review and audit supplier Security and Access, ensuring no changes in their security posture or T&Cs.", "", ""]
],
LLM06: [
["", "", "", "Prevention and mitigation strategies", "Common examples and vulnerabilities", "Example attack scenarios"],
["Subject 6", "LLMs may inadvertently reveal confidential data in their responses, leading to unauthorized data access, privacy violations, and security breaches. It’s crucial to implement data sanitization and strict user policies to mitigate this.", "1", "Integrate adequate data sanitization and scrubbing techniques to prevent user data from entering the training model data.", "Incomplete or improper filtering of sensitive information in the LLM’s responses.", "Unsuspecting legitimate user A is exposed to certain other user data via the LLM when interacting with the LLM application in a non-malicious manner."],
["", "", "2", "Implement robust input validation and sanitization methods to identify and filter out potential malicious inputs to prevent the model from being poisoned.", "Overfitting or memorization of sensitive data in the LLM’s training process.", "User A targets a well-crafted set of prompts to bypass input filters and sanitization from the LLM to cause it to reveal sensitive information (PII) about other users of the \napplication."],
["", "", "3", "When enriching the model with data and if fine-tuning a model: (I.E, data fed into the model before or during deployment).\na. Anything that is deemed sensitive in the fine-tuning data has the potential to be revealed to a user. Therefore, apply the rule of least privilege and do not train the model on information that the highest-privileged user can access which may be displayed to a lower-privileged user.\nb. Access to external data sources (orchestration of data at runtime) should be limited.\nc. Apply strict access control methods to external data sources and a rigorous approach to maintaining a secure supply chain.", "Unintended disclosure of confidential information due to LLM misinterpretation, lack of data scrubbing methods or errors.", "Personal data such as PII is leaked into the model via training data due to either negligence from the user themselves, or the LLM application. This case could increase the risk and probability of scenario 1 or 2 above."]
],
LLM07: [
["", "", "", "Prevention and mitigation strategies", "Common examples and vulnerabilities", "Example attack scenarios"],
["Subject 7", "LLM plugins can have insecure inputs and insufficient access control. This lack of application control makes them easier to exploit and can result in consequences like remote code execution", "1", "Plugins should enforce strict parameterized input wherever possible and include type \nand range checks on inputs. When this is not possible, a second layer of typed calls should be introduced, parsing requests and applying validation and sanitization. When \nfreeform input must be accepted because of application semantics, it should be carefully inspected to ensure no potentially harmful methods are being called.", "A plugin accepts all parameters in a single text field instead of distinct input parameters.", "A plugin accepts a base URL and instructs the LLM to combine the URL with a query to obtain weather forecasts which are included in handling the user request. A malicious user can craft a request such that the URL points to a domain they control, which allows them to inject their own content into the LLM system via their domain."],
["", "", "2", "Plugin developers should apply OWASP’s recommendations in ASVS (Application Security Verification Standard) to ensure adequate input validation and sanitization.", "A plugin accepts configuration strings instead of parameters that can override entire configuration settings. ", "A plugin accepts a free-form input into a single field that it does not validate. An attacker supplies carefully crafted payloads to perform reconnaissance from error \nmessages. It then exploits known third-party vulnerabilities to execute code and perform data exfiltration or privilege escalation."],
["", "", "3", "Plugins should be inspected and tested thoroughly to ensure adequate validation. Use Static Application Security Testing (SAST) scans and Dynamic and Interactive application testing (DAST, IAST) in development pipelines.", "A plugin accepts raw SQL or programming statements instead of parameters.", "A plugin used to retrieve embeddings from a vector store accepts configuration parameters as a connection string without any validation. This allows an attacker to \nexperiment and access other vector stores by changing names or host parameters and exfiltrate embeddings they should not have access to."],
["", "", "4", "Plugins should be designed to minimize the impact of any insecure input parameter exploitation following the OWASP ASVS Access Control Guidelines. This includes \nleast-privilege access control, exposing as little functionality as possible while still performing its desired function.", "Authentication is performed without explicit authorization to a particular plugin.", "A plugin accepts SQL WHERE clauses as advanced filters, which are then appended to the filtering SQL. This allows an attacker to stage a SQL attack."],
["", "", "5", "Plugins should use appropriate authentication identities, such as OAuth2, to apply effective authorization and access control. Additionally, API Keys should be used to provide context for custom authorization decisions that reflect the plugin route rather than the default interactive user.", "A plugin treats all LLM content as being created entirely by the user and performs any requested actions without requiring additional authorization.", "An attacker uses indirect prompt injection to exploit an insecure code management plugin with no input validation and weak access control to transfer repository ownership and lock out the user from their repositories."],
["", "", "6", "Require manual user authorization and confirmation of any action taken by sensitive plugins.", "", ""],
["", "", "7", "Plugins are, typically, REST APIs, so developers should apply the recommendations found in OWASP Top 10 API Security Risks – 2023 to minimize generic vulnerabilities.", "", ""]
],
LLM08: [
["", "", "", "Prevention and mitigation strategies", "Common examples and vulnerabilities", "Example attack scenarios"],
["Subject 8", "LLM-based systems may undertake actions leading to unintended consequences. The issue arises from excessive functionality, permissions, or autonomy granted to the LLM-based systems.", "1", "Limit the plugins/tools that LLM agents are allowed to call to only the minimum functions necessary. For example, if an LLM-based system does not require the ability to fetch the contents of a URL then such a plugin should not be offered to the LLM agent.", "Excessive Functionality: An LLM agent has access to plugins which include functions that are not needed for the intended operation of the system. For example, a developer needs to grant an LLM agent the ability to read documents from a repository, but the 3rd-party plugin they choose to use also includes the ability to modify and delete documents.", "An LLM-based personal assistant app is granted access to an individual’s mailbox via a plugin in order to summarise the content of incoming emails. To achieve this functionality, the email plugin requires the ability to read messages, however the plugin that the system developer has chosen to use also contains functions for sending messages. The LLM is vulnerable to an indirect prompt injection attack, whereby a maliciously-crafted incoming email tricks the LLM into commanding the email plugin to call the 'send message' function to send spam from the user's mailbox. \n\nThis could be avoided by: \n(a) eliminating excessive functionality by using a plugin that only offered mail-reading capabilities, \n(b) eliminating excessive permissions by authenticating to the user's email service via an OAuth session \nwith a read-only scope, and/or \n(c) eliminating excessive autonomy by requiring the user to \nmanually review and hit 'send' on every mail drafted by the LLM plugin. Alternatively, the damage caused could be reduced by implementing rate limiting on the mail-sending \ninterface."],
["", "", "2", "Limit the functions that are implemented in LLM plugins/tools to the minimum necessary. For example, a plugin that accesses a user's mailbox to summarise emails \nmay only require the ability to read emails, so the plugin should not contain other functionality such as deleting or sending messages.", "Excessive Functionality: A plugin may have been trialed during a development phase and dropped in favor of a better alternative, but the original plugin remains available to the LLM agent.", ""],
["", "", "3", "Avoid open-ended functions where possible (e.g., run a shell command, fetch a URL, etc.) and use plugins/tools with more granular functionality. For example, an LLM based app may need to write some output to a file. If this were implemented using a plugin to run a shell function then the scope for undesirable actions is very large (any \nother shell command could be executed). A more secure alternative would be to build a file-writing plugin that could only support that specific functionality.", "Excessive Functionality: An LLM plugin with open-ended functionality fails to properly filter the input instructions for commands outside what's necessary for the intended operation of the application. E.g., a plugin to run one specific shell command fails to properly prevent other shell commands from being executed.", ""],
["", "", "4", "Limit the permissions that LLM plugins/tools are granted to other systems to the minimum necessary in order to limit the scope of undesirable actions. For example, an LLM agent that uses a product database in order to make purchase recommendations to a customer might only need read access to a 'products' table; it should not have access to other tables, nor the ability to insert, update or delete records. This should be enforced by applying appropriate database permissions for the identity that the LLM plugin uses to connect to the database.", "Excessive Permissions: An LLM plugin has permissions on other systems that are not needed for the intended operation of the application. E.g., a plugin intended to read data connects to a database server using an identity that not only has SELECT permissions, but also UPDATE, INSERT and DELETE permissions.", ""],
["", "", "5", "Track user authorization and security scope to ensure actions taken on behalf of a user are executed on downstream systems in the context of that specific user, and with the minimum privileges necessary. For example, an LLM plugin that reads a user's code repo should require the user to authenticate via OAuth and with the minimum scope required.", "Excessive Permissions: An LLM plugin that is designed to perform operations on behalf of a user accesses downstream systems with a generic high-privileged identity. E.g., a plugin to read the current user's document store connects to the document repository with a privileged account that has access to all users' files", ""],
["", "", "6", "Utilise human-in-the-loop control to require a human to approve all actions before they \nare taken. This may be implemented in a downstream system (outside the scope of the LLM application) or within the LLM plugin/tool itself. For example, an LLM-based \napp that creates and posts social media content on behalf of a user should include a user approval routine within the plugin/tool/API that implements the 'post' operation.", "Excessive Autonomy: An LLM-based application or plugin fails to independently verify and approve high-impact actions. E.g., a plugin that allows a user's documents to be \ndeleted performs deletions without any confirmation from the user.", ""],
["", "", "7", "Implement authorization in downstream systems rather than relying on an LLM to decide if an action is allowed or not. When implementing tools/plugins enforce the complete mediation principle so that all requests made to downstream systems via the plugins/tools are validated against security policies.", "", ""]
],
LLM09: [
["", "", "", "Prevention and mitigation strategies", "Common examples and vulnerabilities", "Example attack scenarios"],
["Subject 9", "Systems or people overly depending on LLMs without oversight may face misinformation,miscommunication, legal issues, and security vulnerabilities due to incorrect or inappropriate content generated by LLMs.", "1", "Regularly monitor and review the LLM outputs. Use self-consistency or voting techniques to filter out inconsistent text. Comparing multiple model responses for a single prompt can better judge the quality and consistency of output.", "LLM provides inaccurate information as a response while stating it in a fashion \nimplying it is highly authoritative. The overall system is designed without proper checks and balances to handle this and the information misleads the user in a way that leads to harm.", "A news organization heavily uses an LLM to generate news articles. A malicious actor exploits this over-reliance, feeding the LLM misleading information, and causing the spread of disinformation."],
["", "", "2", "Cross-check the LLM output with trusted external sources. This additional layer of validation can help ensure the information provided by the model is accurate and reliable.", "LLM suggests insecure or faulty code, leading to vulnerabilities when incorporated into a software system without proper oversight or verification.", "The AI unintentionally plagiarizes content, leading to copyright issues and decreased trust in the organization."],
["", "", "3", "Enhance the model with fine-tuning or embeddings to improve output quality. Generic pre-trained models are more likely to produce inaccurate information compared to tuned models in a particular domain. Techniques such as prompt engineering, parameter efficient tuning (PET), full model tuning, and chain of thought prompting can \nbe employed for this purpose.", "", "A software development team utilizes an LLM system to expedite the coding process. Over-reliance on the AI's suggestions introduces security vulnerabilities in the application due to insecure default settings or recommendations inconsistent with secure coding practices."],
["", "", "4", "Implement automatic validation mechanisms that can cross-verify the generated output against known facts or data. This can provide an additional layer of security and \nmitigate the risks associated with hallucinations.", "", "A software development firm uses an LLM to assist developers. The LLM suggests a non-existent code library or package, and a developer, trusting the AI, unknowingly integrates a malicious package into the firm's software. This highlights the importance of cross-checking LLM suggestions, especially when involving third-party code or \nlibraries."],
["", "", "5", "Break down complex tasks into manageable subtasks and assign them to different agents. This not only helps in managing complexity, but it also reduces the chances of hallucinations as each agent can be held accountable for a smaller task.", "", ""],
["", "", "6", "Clearly communicate the risks and limitations associated with using LLMs. This includes potential for information inaccuracies, and other risks. Effective risk communication can prepare users for potential issues and help them make informed \ndecisions.", "", ""],
["", "", "7", "Build APIs and user interfaces that encourage responsible and safe use of LLMs. This can involve measures such as content filters, user warnings about potential inaccuracies, and clear labeling of AI-generated content.", "", ""],
["", "", "8", "When using LLMs in development environments, establish secure coding practices and guidelines to prevent the integration of possible vulnerabilities.", "", ""]
],
LLM010: [
["", "", "", "Prevention and mitigation strategies", "Prevention (cont)", "Common examples and vulnerabilities", "Example attack scenarios"],
["Subject 10", "This involves unauthorized access, copying, or exfiltration of proprietary LLM models. The impact includes economic losses, compromised competitive advantage, and potential access to sensitive information", "1", "Implement strong access controls (E.G., RBAC and rule of least privilege) and strong authentication mechanisms to limit unauthorized access to LLM model repositories and training environments.", "a. This is particularly true for the first three common examples, which could cause this vulnerability due to insider threats, misconfiguration, and/or weak security controls about the infrastructure that houses LLM models, weights and architecture in which a malicious actor could infiltrate from insider or outside the environment", "An attacker exploits a vulnerability in a company's infrastructure to gain unauthorized access to their LLM model repository via misconfiguration in their network or application security settings.", " An attacker exploits a vulnerability in a company's infrastructure to gain unauthorized access to their LLM model repository. The attacker proceeds to exfiltrate valuable LLM \nmodels and uses them to launch a competing language processing service or extract sensitive information, causing significant financial harm to the original company."],
["", "", "", "", "b. Supplier management tracking, verification and dependency vulnerabilities are important focus topics to prevent exploits of supply-chain attacks.", "", ""],
["", "", "2", "Restrict the LLM's access to network resources, internal services, and APIs.", "a. This is particularly true for all common examples as it covers insider risk and threats, but also ultimately controls what the LLM application \"has access to\" and thus could be a mechanism or prevention step to prevent side-channel attacks.", "Use a centralized ML Model Inventory or Registry for ML models used in production. Having a centralized model registry prevents unauthorized access to ML Models via access controls, authentication, and monitoring/logging capability which are good foundations for governance. Having a centralized repository is also beneficial for \ncollecting data about algorithms used by the models for the purposes of compliance, risk assessments, and risk mitigation.", "A disgruntled employee leaks model or related artifacts. The public exposure of this scenario increases knowledge to attackers for gray box adversarial attacks or alternatively directly steal the available property."],
["", "", "3", "Regularly monitor and audit access logs and activities related to LLM model repositories to detect and respond to any suspicious or unauthorized behavior \npromptly.", "", "An insider threat scenario where a disgruntled employee leaks model or related artifacts.", "An attacker queries the API with carefully selected inputs and collects sufficient number of outputs to create a shadow model."],
["", "", "4", "Automate MLOps deployment with governance and tracking and approval workflows to tighten access and deployment controls within the infrastructure.", "", "An attacker queries the model API using carefully crafted inputs and prompt injection techniques to collect a sufficient number of outputs to create a shadow mode.", "A security control failure is present within the supply-chain and leads to data leaks of proprietary model information."],
["", "", "5", "Implement controls and mitigation strategies to mitigate and|or reduce risk of prompt injection techniques causing side-channel attacks.", "", "A malicious attacker is able to bypass input filtering techniques of the LLM to perform a side-channel attack and ultimately harvest model weights and architecture information to a remote controlled resource.", "A malicious attacker bypasses input filtering techniques and preambles of the LLM to perform a side-channel attack and retrieve model information to a remote controlled resource under their control."],
["", "", "6", "Rate Limiting of API calls where applicable and|or filters to reduce risk of data exfiltration from the LLM applications, or implement techniques to detect (E.G., DLP) extraction activity from other monitoring systems.", "", "The attack vector for model extraction involves querying the LLM with a large number of prompts on a particular topic. The outputs from the LLM can then be used to finetune another model. However, there are a few things to note about this attack:\n\n1. The attacker must generate a large number of targeted prompts. If the prompts are not specific enough, the outputs from the LLM will be useless.\n2. The outputs from LLMs can sometimes contain hallucinated answers meaning the attacker may not be able to extract the entire model as some of the outputs can be nonsensical.\n2a. It is not possible to replicate an LLM 100% through model extraction. However, the attacker will be able to replicate a partial model.", ""],
["", "", "7", "Implement adversarial robustness training to help detect extraction queries and tighten physical security measures.", "", "The attack vector for functional model replication involves using the target model via prompts to generate synthetic training data (an approach called \"self-instruct\") to then \nuse it and fine-tune another foundational model to produce a functional equivalent.This bypasses the limitations of traditional query-based extraction used in Example 5 \nand has been successfully used in research of using an LLM to train another LLM. Although in the context of this research, model replication is not an attack. The approach could be used by an attacker to replicate a proprietary model with a public \nAPI.", ""],
["", "", "8", "Implement a watermarking framework into the embedding and detection stages of an LLMs lifecyle.", "", "", ""]
]
  };